![](../docs/banner.png)

# NumPy

**Tomas Beuzen, September 2020**

These exercises complement [Chapter 5](../chapters/chapter5-numpy.ipynb) and [Chapter 6](../chapters/chapter6-numpy-addendum.ipynb).

## Exercises

### 1.

Import numpy under the alias `np`.

In [2]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [5]:
zeros_array = np.zeros(5)
ones_array = np.ones(10)
pi_arrays = np.full(5, 3.141)
one_twenty = np.arange(1, 21)
matrix = np.ones((5, 5), dtype=int)
print(zeros_array, ones_array, pi_arrays, one_twenty, matrix)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [3.141 3.141 3.141 3.141 3.141] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [8]:
random_matrix = np.random.randn(3, 3, 3)
reshaped_matrix = random_matrix.reshape(27)
print(random_matrix)
print(reshaped_matrix)

[[[ 0.72078897 -0.37416827 -1.4240585 ]
  [-1.12749715  0.2943612  -2.02092932]
  [-0.81169976 -1.35696731  1.32479246]]

 [[ 1.02926981 -0.16152802  0.57584771]
  [-1.61163791  0.39153222 -0.31251807]
  [ 0.62154035  1.50372807  0.2962233 ]]

 [[ 0.49802291  0.06135038  0.68982405]
  [ 1.25411083  1.36886901  0.00862224]
  [-1.52825638  0.68127777 -0.06830908]]]
[ 0.72078897 -0.37416827 -1.4240585  -1.12749715  0.2943612  -2.02092932
 -0.81169976 -1.35696731  1.32479246  1.02926981 -0.16152802  0.57584771
 -1.61163791  0.39153222 -0.31251807  0.62154035  1.50372807  0.2962233
  0.49802291  0.06135038  0.68982405  1.25411083  1.36886901  0.00862224
 -1.52825638  0.68127777 -0.06830908]


### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [9]:
linear = np.linspace(1, 10, 20)
print(linear)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [11]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


```python
20
```

In [16]:
print (a[3,4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [17]:
print(a[1: ,3: ])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [19]:
print(a[1:2])

[[ 6  7  8  9 10]]


```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [22]:
print(a[2:4])

[[11 12 13 14 15]
 [16 17 18 19 20]]


```python
array([[ 8,  9],
       [13, 14]])
```

In [30]:
print(a[1:3 , 2:4])

[[ 8  9]
 [13 14]]


### 6.

Calculate the sum of all the numbers in `a`.

In [32]:
total_sum = np.sum(a)
print(total_sum)

325


### 7.

Calculate the sum of each row in `a`.

In [34]:
print(np.sum(a, axis=1))

[ 15  40  65  90 115]


### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [35]:
mean = np.mean(a)
mask = a > mean
print (a[mask])

[14 15 16 17 18 19 20 21 22 23 24 25]


### 9.

Find the location of the minimum value in the following array `b`:

In [36]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [38]:
print (np.argmin(b))

6


### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [39]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [41]:
print(np.max(c))
print (np.argmax(c))

1.651436537097151
5


<hr>
<hr>
<hr>